name: release-matrix
on:
  schedule:
    - cron: "0 2 * * 0"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      flavor:
        description: "Flavor to build"
        required: true
        default: "base-generic"
        type: choice
        options:
          - base-generic
          - base-intel
          - base-amd
          - base-nvidia-legacy
          - base-nvidia-mainstream
          - base-nvidia-bleeding
          - base-nvidia-datacenter
          - docker-generic
          - docker-intel
          - docker-amd
          - docker-nvidia
          - docker-nvidia-bleeding
          - podman-generic
          - k8s-node-generic
          - k8s-node-cilium
          - k8s-node-calico
          - k8s-node-flannel
          - k8s-node-intel
          - k8s-node-amd
          - k8s-node-nvidia
          - k8s-node-nvidia-bleeding
          - ai-infer-generic
          - ai-infer-intel
          - ai-infer-amd
          - ai-infer-nvidia
          - ai-infer-nvidia-bleeding


permissions:
  contents: write
  packages: write
  id-token: write

env:
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-matrix:
    name: Build Image (${{ matrix.flavor }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - base-generic
          - docker-generic
          - k8s-node-generic
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3.1.0
        with:
          version: "1.11.2"
      - name: Install QEMU and Zstd
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 qemu-utils zstd
      - name: Build Image with Packer
        run: |
          cd packer
          packer init .
          packer build -only="${{ matrix.flavor }}.qemu.image" .
      - name: Compress Image with Zstandard
        run: |
          cd output-images/${{ matrix.flavor }}
          zstd -T0 -19 --rm *.qcow2
          sha256sum *.qcow2.zst > SHA256SUMS
      - name: Upload Release Artifacts
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            output-images/${{ matrix.flavor }}/*.qcow2.zst
            output-images/${{ matrix.flavor }}/SHA256SUMS
